name: WarpSystem
author: CodingAir
version: '4.0.10'
description: WarpSystem
main: de.codingair.warpsystem.spigot.base.WarpSystem
softdepend: [Multiverse-Core, Vault, Essentials, MultiWorld]
api-version: 1.13

commands:
  warp:
    usuage: /Warp
    description: A Warp-System-CMD
  warps:
    usuage: /Warps
    description: A Warp-System-CMD
  warpsystem:
    usuage: /WarpSystem
    description: A Warp-System-CMD
    aliases: [ws]
  portal:
    usuage: /Portal
    description: A Warp-System-CMD
    aliases: [portals]
  globalwarps:
    ususage: /GlobalWarps
    description: A Warp-System-CMD
    aliases: [gws, gwarps]
  globalwarp:
    ususage: /GlobalWarp
    description: A Warp-System-CMD
    aliases: [gw, gwarp]
  nativeportals:
    usuage: /NativePortals
    description: A Warp-System-CMD
    aliases: [nativeportal, np, nps]
  tempwarps:
    usuage: /TempWarps
    description: A Warp-System-CMD
    aliases: [tws, twarps]
  tempwarp:
    usuage: /TempWarp
    description: A Warp-System-CMD
    aliases: [tw, twarp]
  setwarp:
    usuage: /SetWarp
    description: A Warp-System-CMD
  deletewarp:
    usuage: /DeleteWarp
    description: A Warp-System-CMD
    aliases: [delwarp]
  editwarp:
    usuage: /EditWarp
    description: A Warp-System-CMD
  randomtp:
    usuage: /RandomTP
    description: A Warp-System-CMD
  teleport:
    usuage: /teleport <player> [player]
    description: A Warp-System-CMD
    aliases: [tp]

permissions:
  warpsystem:
    default: op
    description: Default start of each permission node
    children:
      warpsystem.notify: true
      warpsystem.admin: true
      warpsystem.modify.*: true
      warpsystem.use.*: true
      warpsystem.bypass.*: true
      warpsystem.teleport.*: true
  warpsystem.modify.*:
    description: notify for warnings or new updates
    children:
      warpsystem.modify: true
      warpsystem.modify.icons: true
      warpsystem.modify.warpSigns: true
      warpsystem.modify.globalwarps: true
      warpsystem.modify.simplewarps: true
      warpsystem.modify.portals: true
      warpsystem.modify.nativeportals: true
      warpsystem.modify.randomteleporters: true
  warpsystem.use.*:
    description: Player can use features
    children:
      warpsystem.use.warps: true
      warpsystem.use.warpSigns: true
      warpsystem.use.tempwarps: true
      warpsystem.use.globalwarps: true
      warpsystem.use.simplewarps: true
      warpsystem.use.portals: true
      warpsystem.use.nativeportals: true
      warpsystem.use.randomteleporters: true
  warpsystem.bypass.*:
    description: Permission to bypass different things
    children:
      warpsystem.bypass.teleport.*: true
      warpsystem.bypass.maintenance: true
  warpsystem.bypass.teleport.*:
    description: Permission to bypass teleport parameters
    children:
      warpsystem.bypass.teleport.costs: true
      warpsystem.bypass.teleport.delay: true
  warpsystem.teleport.*:
    description: Extra things for teleports
    children:
      warpsystem.teleport.chunkpreloading: true