name: WarpSystem
author: CodingAir
version: '4.1.4'
description: WarpSystem
main: de.codingair.warpsystem.spigot.base.WarpSystem
softdepend: [Multiverse-Core, Vault, Essentials, MultiWorld]
api-version: 1.13